name: CI-CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Validate Code
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Synk Check for vulnerabilities
        uses: snyk/actions/node@master
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
        with:
            args: --severity-threshold=high --all-projects

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Send Success email
        if : success() && github.event_name == 'push' 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Pipeline Success: ${{ github.repository }}"
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions CI
          body: |
            The build for ${{ github.repository }} succeeded!
            Commit: ${{ github.sha }}
            View Results: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # Email Notification - Runs on Failure
      - name: Send Failure Email
        if: failure() && github.event_name == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Pipeline FAILED: ${{ github.repository }}"
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions CI
          body: |
            The build for ${{ github.repository }} failed during the validation stage.
            Please check the logs immediately.